export const banks = [
  {
    name: "Abay Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/11/Abay-Bank-Vacancy-min-128x128.png",
    website: "https://www.abaybank.com.et/",
    link: "https://banksethiopia.com/banks/abay-bank/",
  },
  {
    name: "Addis International Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/12/21370834_296269067447274_1806288827891586186_n-128x128.png",
    website: "https://addisbanksc.com/",
    link: "https://banksethiopia.com/banks/addis-international-bank/",
  },
  {
    name: "Ahadu Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/ahadu-logo-128x128.jpeg",
    website: "https://www.ahadubank.com/",
    link: "https://banksethiopia.com/banks/ahadu-bank/",
  },
  {
    name: "Amhara Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2022/07/Amhara-bank-to-start-operation-sene-11-2014-2-128x128.jpg",
    website: "https://amharabank.com.et/about/",
    link: "https://banksethiopia.com/banks/amhara-bank/",
  },
  {
    name: "Awash Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/awash-bank-1.png",
    website: "https://www.awashbank.com",
    link: "https://banksethiopia.com/banks/awash-bank/",
  },
  {
    name: "Bank of Abyssinia",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/10/abyssinia-bank-logo-profit-financial-statement-shareholder-e1685430860462-128x100.jpg",
    website: "https://www.bankofabyssinia.com/",
    link: "https://banksethiopia.com/banks/bank-of-abyssinia/",
  },
  {
    name: "Berhan Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/11/78805639_104067677739540_679823452428828672_n-128x128.jpg",
    website: "https://berhanbanksc.com/",
    link: "https://banksethiopia.com/banks/berhan-bank/",
  },
  {
    name: "Bunna Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/bunna-bank-logo-128x128.png",
    website: "https://bunnabanksc.com/",
    link: "https://banksethiopia.com/banks/bunna-bank/",
  },
  {
    name: "Commercial Bank of Ethiopia (CBE)",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/10/unnamed-1-128x128.png",
    website: "https://combanketh.et/",
    link: "https://banksethiopia.com/banks/commercial-bank-of-ethiopia/",
  },
  {
    name: "Cooperative Bank of Oromia",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/12/44594476_1799472196845381_7959294240301776896_n-128x128.jpg",
    website: "https://www.coopbankoromia.com.et/",
    link: "https://banksethiopia.com/banks/cooperative-bank-of-oromia/",
  },
  {
    name: "Dashen Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/10/2-128x128.png",
    website: "https://dashenbanksc.com",
    link: "https://banksethiopia.com/banks/dashen-bank/",
  },
  {
    name: "Enat Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/11/logo-for-profile-128x128.png",
    website: "https://www.enatbanksc.com",
    link: "https://banksethiopia.com/banks/enat-bank/",
  },
  {
    name: "Global Bank Ethiopia",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/12/91629292_104207271242jh238_364847266952904704_n-128x128.jpg",
    website: "https://debubglobalbank.com/",
    link: "https://banksethiopia.com/banks/debub-global-bank/",
  },
  {
    name: "Gadaa Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/gada-bank-small-128x128.png",
    website: "https://gadaabank.com.et/",
    link: "https://banksethiopia.com/banks/gadaa-bank-review/",
  },
  {
    name: "Hibret Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/10/index-128x128.png",
    website: "https://www.hibretbank.com.et/",
    link: "https://banksethiopia.com/banks/hibret-bank/",
  },
  {
    name: "Lion Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/12/53092_17626617571880hg0_5221808_o-128x128.jpg",
    website: "https://anbesabank.com/",
    link: "https://banksethiopia.com/banks/lion-bank/",
  },
  {
    name: "Hijra Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/index-128x128.jpeg",
    website: "https://hijra-bank.com/",
    link: "https://banksethiopia.com/banks/hijira-bank/",
  },
  {
    name: "Oromia Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/OROMIABANK-LOGO-1-128x128.jpg",
    website: "https://www.oromiabank.com/",
    link: "https://banksethiopia.com/banks/oromia-bank/",
  },
  {
    name: "Nib Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/10/download-1-128x128.jpg",
    website: "https://www.nibbanksc.com",
    link: "https://banksethiopia.com/banks/nib-bank/",
  },
  {
    name: "Siinqee Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/siinquee-bankfor-pc-128x128.png",
    website: "http://www.siinqeebank.com",
    link: "https://banksethiopia.com/banks/siinqee-bank/",
  },
  {
    name: "Shabelle Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/1200x630wa-128x128.png",
    website: "https://shabellebank.com/",
    link: "https://banksethiopia.com/banks/shabelle-bank/",
  },
  {
    name: "Tsehay Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/tsehay-bank4-128x128.jpeg",
    website: "https://tsehaybank.com.et/",
    link: "https://banksethiopia.com/banks/tsehay-bank/",
  },
  {
    name: "Tsedey Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/tsedey-bank2-128x128.jpg",
    website: "https://tsedeybank-sc.com/",
    link: "https://banksethiopia.com/banks/tsedey-bank-review/",
  },
  {
    name: "ZamZam Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/zamzam-bank-logo-1-128x128.jpg",
    website: "https://zamzambank.com/",
    link: "https://banksethiopia.com/banks/zamzam-bank/",
  },
  {
    name: "Wegagen Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/2020/11/comitted-logo-300x233-1-128x128.png",
    website: "https://www.wegagen.com/",
    link: "https://banksethiopia.com/banks/wegagen-bank/",
  },
  {
    name: "Zemen Bank",
    logo: "https://banksethiopia.com/wp-content/uploads/zemen-bank-review-128x128.png",
    website: "https://www.zemenbank.com/",
    link: "https://banksethiopia.com/banks/zemen-bank/",
  },
];

export const paymentMethods = [
  { name: "E-Birr", local: true },
  { name: "Awash Birr", local: true },
  { name: "Paypal", local: false },
  { name: "Master Card", local: false },
  { name: "TeleBirr", local: true },
  { name: "Wegagen", local: true },
  { name: "CBE Birr", local: true },
  { name: "Amole", local: true },
  { name: "BOA", local: true },
];
